// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_metric.sql

package pgen

import (
	"context"
)

const getByName = `-- name: GetByName :one
SELECT id, name, type, value, delta, hash, created_at, updated_at FROM metric.metrics WHERE name = $1
`

func (q *Queries) GetByName(ctx context.Context, name string) (MetricMetric, error) {
	row := q.db.QueryRow(ctx, getByName, name)
	var i MetricMetric
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.Delta,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
