// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ipsert_metric.sql

package pgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsert = `-- name: Upsert :exec
INSERT INTO metric.metrics (name, type, value, delta, hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name, hash)
DO UPDATE SET
value = EXCLUDED.value, delta = EXCLUDED.delta, updated_at = NOW()
`

type UpsertParams struct {
	Name  string        `json:"name"`
	Type  string        `json:"type"`
	Value pgtype.Float8 `json:"value"`
	Delta pgtype.Int8   `json:"delta"`
	Hash  pgtype.Text   `json:"hash"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) error {
	_, err := q.db.Exec(ctx, upsert,
		arg.Name,
		arg.Type,
		arg.Value,
		arg.Delta,
		arg.Hash,
	)
	return err
}
