// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_metrics.sql

package pgen

import (
	"context"
)

const list = `-- name: List :many
SELECT id, name, type, value, delta, hash, created_at, updated_at FROM metric.metrics
`

func (q *Queries) List(ctx context.Context) ([]MetricMetric, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricMetric
	for rows.Next() {
		var i MetricMetric
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Value,
			&i.Delta,
			&i.Hash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
