// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MetricMetric struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	Value     pgtype.Float8    `json:"value"`
	Delta     pgtype.Int8      `json:"delta"`
	Hash      pgtype.Text      `json:"hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
