// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgen

import (
	"context"
)

type Querier interface {
	// BatchUpsert через jsonb_to_recordset
	// Смотрите инструкцию для параметра `BatchUpsertParam` в `internal/adapters/postgres/pgen/custom_params.go`
	BatchUpsert(ctx context.Context, metrics []byte) error
	GetByName(ctx context.Context, name string) (MetricMetric, error)
	List(ctx context.Context) ([]MetricMetric, error)
}

var _ Querier = (*Queries)(nil)
