// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgen

import (
	"context"
)

type Querier interface {
	GetByName(ctx context.Context, name string) (MetricMetric, error)
	List(ctx context.Context) ([]MetricMetric, error)
	Upsert(ctx context.Context, arg UpsertParams) error
}

var _ Querier = (*Queries)(nil)
