// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/applications/metrics (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=./internal/applications/metrics/mock_repository_test.go -package=metrics -mock_names Repository=MockRepository ./internal/applications/metrics Repository
//

// Package metrics is a generated GoMock package.
package metrics

import (
	context "context"
	reflect "reflect"

	metrics0 "github.com/76Parker/metrico/internal/domain/metrics"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockRepository) Apply(ctx context.Context, mutations []Change) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, mutations)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockRepositoryMockRecorder) Apply(ctx, mutations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockRepository)(nil).Apply), ctx, mutations)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, metricName string) (metrics0.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricName)
	ret0, _ := ret[0].(metrics0.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, metricName)
}

// GetAll mocks base method.
func (m *MockRepository) GetAll(ctx context.Context) ([]metrics0.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]metrics0.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll), ctx)
}
