// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/health (interfaces: dbPinger)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/health/mock_ports.go -package=health ./internal/usecase/health dbPinger
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockdbPinger is a mock of dbPinger interface.
type MockdbPinger struct {
	ctrl     *gomock.Controller
	recorder *MockdbPingerMockRecorder
	isgomock struct{}
}

// MockdbPingerMockRecorder is the mock recorder for MockdbPinger.
type MockdbPingerMockRecorder struct {
	mock *MockdbPinger
}

// NewMockdbPinger creates a new mock instance.
func NewMockdbPinger(ctrl *gomock.Controller) *MockdbPinger {
	mock := &MockdbPinger{ctrl: ctrl}
	mock.recorder = &MockdbPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbPinger) EXPECT() *MockdbPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockdbPinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockdbPingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockdbPinger)(nil).Ping), ctx)
}
