// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/metrics (interfaces: metricStorage)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/metrics/mock_ports.go -package=metrics ./internal/usecase/metrics metricStorage
//

// Package metrics is a generated GoMock package.
package metrics

import (
	context "context"
	reflect "reflect"

	metrics "github.com/76Parker/metrico/internal/domain/metrics"
	gomock "go.uber.org/mock/gomock"
)

// MockmetricStorage is a mock of metricStorage interface.
type MockmetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockmetricStorageMockRecorder
	isgomock struct{}
}

// MockmetricStorageMockRecorder is the mock recorder for MockmetricStorage.
type MockmetricStorageMockRecorder struct {
	mock *MockmetricStorage
}

// NewMockmetricStorage creates a new mock instance.
func NewMockmetricStorage(ctrl *gomock.Controller) *MockmetricStorage {
	mock := &MockmetricStorage{ctrl: ctrl}
	mock.recorder = &MockmetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricStorage) EXPECT() *MockmetricStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockmetricStorage) Get(ctx context.Context, metricName string) (metrics.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricName)
	ret0, _ := ret[0].(metrics.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockmetricStorageMockRecorder) Get(ctx, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockmetricStorage)(nil).Get), ctx, metricName)
}

// GetAll mocks base method.
func (m *MockmetricStorage) GetAll(ctx context.Context) ([]metrics.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]metrics.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockmetricStorageMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockmetricStorage)(nil).GetAll), ctx)
}

// UpdateOrCreate mocks base method.
func (m *MockmetricStorage) UpdateOrCreate(ctx context.Context, metricName string, metric metrics.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrCreate", ctx, metricName, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrCreate indicates an expected call of UpdateOrCreate.
func (mr *MockmetricStorageMockRecorder) UpdateOrCreate(ctx, metricName, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrCreate", reflect.TypeOf((*MockmetricStorage)(nil).UpdateOrCreate), ctx, metricName, metric)
}
