// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package snapshotschema

import (
	"encoding/json"
	"fmt"
	"reflect"
)

type Metric struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Type corresponds to the JSON schema field "type".
	Type MetricType `json:"type" yaml:"type" mapstructure:"type"`

	// Delta corresponds to the JSON schema field "delta".
	Delta *int64 `json:"delta,omitempty,omitzero" yaml:"delta,omitempty" mapstructure:"delta,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *float64 `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

type MetricType string

const MetricTypeCounter MetricType = "counter"
const MetricTypeGauge MetricType = "gauge"

var enumValues_MetricType = []interface{}{
	"counter",
	"gauge",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MetricType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MetricType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MetricType, v)
	}
	*j = MetricType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Metric) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Metric: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Metric: required")
	}
	type Plain Metric
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Metric(plain)
	return nil
}

type MetricsSnapshotV1SchemaJson []Metric
