// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/api/handlers (interfaces: metricsApplication)
//
// Generated by this command:
//
//	mockgen -destination=./internal/api/handlers/mock_metrics_application_test.go -package=handlers -mock_names metricsApplication=MockMetricsApplication ./internal/api/handlers metricsApplication
//

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	metrics "github.com/76Parker/metrico/internal/applications/metrics"
	metrics0 "github.com/76Parker/metrico/internal/domain/metrics"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsApplication is a mock of metricsApplication interface.
type MockMetricsApplication struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsApplicationMockRecorder
	isgomock struct{}
}

// MockMetricsApplicationMockRecorder is the mock recorder for MockMetricsApplication.
type MockMetricsApplicationMockRecorder struct {
	mock *MockMetricsApplication
}

// NewMockMetricsApplication creates a new mock instance.
func NewMockMetricsApplication(ctrl *gomock.Controller) *MockMetricsApplication {
	mock := &MockMetricsApplication{ctrl: ctrl}
	mock.recorder = &MockMetricsApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsApplication) EXPECT() *MockMetricsApplicationMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockMetricsApplication) BatchUpdate(ctx context.Context, cmd metrics.BatchUpdateCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockMetricsApplicationMockRecorder) BatchUpdate(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockMetricsApplication)(nil).BatchUpdate), ctx, cmd)
}

// GetAll mocks base method.
func (m *MockMetricsApplication) GetAll(ctx context.Context) ([]metrics0.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]metrics0.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMetricsApplicationMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMetricsApplication)(nil).GetAll), ctx)
}

// GetByName mocks base method.
func (m *MockMetricsApplication) GetByName(ctx context.Context, name string) (metrics0.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(metrics0.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockMetricsApplicationMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockMetricsApplication)(nil).GetByName), ctx, name)
}

// Update mocks base method.
func (m *MockMetricsApplication) Update(ctx context.Context, cmd metrics.UpdateCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricsApplicationMockRecorder) Update(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricsApplication)(nil).Update), ctx, cmd)
}
