// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/applications/health (interfaces: dbPinger)
//
// Generated by this command:
//
//	mockgen -destination=./internal/applications/health/mock_db_pinger_test.go -package=health -mock_names dbPinger=MockDbPinger ./internal/applications/health dbPinger
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDbPinger is a mock of dbPinger interface.
type MockDbPinger struct {
	ctrl     *gomock.Controller
	recorder *MockDbPingerMockRecorder
	isgomock struct{}
}

// MockDbPingerMockRecorder is the mock recorder for MockDbPinger.
type MockDbPingerMockRecorder struct {
	mock *MockDbPinger
}

// NewMockDbPinger creates a new mock instance.
func NewMockDbPinger(ctrl *gomock.Controller) *MockDbPinger {
	mock := &MockDbPinger{ctrl: ctrl}
	mock.recorder = &MockDbPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbPinger) EXPECT() *MockDbPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDbPinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDbPingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDbPinger)(nil).Ping), ctx)
}
